name: Bug report
description: Create a report to help us improve
title: '[Bug] '
labels: ['issue::bug']
type: Bug
assignees: []
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: impact-description
    attributes:
      label: Impact of the bug
      description: What is the impact of this bug on you or other users?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround (if any)
      description: Describe any temporary workarounds you have found.
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Is a fix for this issue urgent?
      options:
        - High
        - Low
    validations:
      required: true

  - type: dropdown
    id: importance
    attributes:
      label: How important is this issue?
      options:
        - High
        - Low
    validations:
      required: true

  - type: input
    id: sw-version
    attributes:
      label: SW Version
    validations:
      required: false

  - type: input
    id: fw-version
    attributes:
      label: FW Version
    validations:
      required: false

  - type: dropdown
    id: customer-release
    attributes:
      label: Does the issue occur in a customer release?
      options:
        - yes
        - no
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. Include screenshots, error messages, or logs if possible.
    validations:
      required: false
